title: "New Hugo Website" # Website name
baseURL: "https://mudassir-nawaz.github.io/berrybower/" # Website URL

############################
## ADVANCED
############################

build:
  writeStats: true
