title: "New Hugo Website" # Website name
baseURL: "https://mudassir-nawaz.github.io/berrybower/" # Website URL

############################
## ADVANCED
############################

build:
  writeStats: true

markup:
  highlight:
    style: rrt
    noClasses: false
    lineNos: true


############################
## EXTERNAL SERVICES
############################
services:
  googleAnalytics:
    ID: "G-MEASUREMENT_ID" ##### google analytics id