main:
  - name: "Home"
    url: "/"
    weight: 1
  - name: "Solutions"
    weight: 2
  - name: "Web"
    url: "/"
    parent: "Solutions"
    weight: 1
  - name: "App"
    url: "/"
    parent: "Solutions"
    weight: 2
  - name: "Desktop"
    url: "/"
    parent: "Solutions"
    weight: 3
  - name: "Resources"
    url: "resources/"
    weight: 3
  - name: "Pricing"
    url: "pricing/"
    weight: 4
  - name: "Pricing"
    url: "pricing/"
    weight: 5

footer:
  - name: "Home"
    url: /
    weight: 1
  - name: "Pricing/Packages"
    url: "pricing/"
    weight: 2
  - name: "About Us"
    url: "about/"
    weight: 3
  - name: "Contact"
    url: "contact/"
    weight: 4
  - name: "Privacy Policy"
    url: "policies/"
    weight: 5
  - name: "Terms & Conditions"
    url: "terms/"
    weight: 6

solutions:
  - name: "Exploit and Vulnerability Intelligence"
    url: "ev-intelligence/"
    weight: 1
  - name: "Critical Vulnerability Prioritization"
    url: "cv-priority"
    weight: 2

resources:
  - name: "API"
    url: "api/"
    weight: 1
  - name: "Documentation"
    url: "docs/"
    weight: 2
