light_logo: "images/dark_logo.png" ##### Header and Footer logo for light theme
dark_logo: "images/light_logo.png" ##### Header and Footer logo for dark theme

header_login_btn: ##### Header login button
  label: "Login"
  url: "/"
cta_btn: ##### Header & Footer call-to-action button
  label: "Schedule Demo"
  url: "our-vision/"

newsletter:  ##### Hide/Show newsletter box from the footer
  enable: true

copyright: "© 2024 All Rights Reserved VulneraWise." ##### Site copyright text

github: "/" ##### Footer Github icon link
twitter: "/" ##### Footer Twitter icon link
linkedin: "/" ##### Footer LinkedIn icon link